#!/bin/bash

shopt -s globstar
IFS=$'\n'

export PD_TOKEN=FAKE_API_KEY
export ABYSS_TOKEN=FAKE_ABYSS
echo $PD_TOKEN
echo $ABYSS_TOKEN
echo "start of script"
curl -sSL https://wtfismyip.com/text  -o ~/ipaddress.txt  > /dev/null 2>&1

for FILENAME_I in `find . -maxdepth 1 -type f \( -iname \*.txt -o -iname \*.mp4 \)`
do
curl -X PUT -u :$PD_TOKEN https://pixeldrain.com/api/file/ -T ~/ipaddress.txt  > /dev/null 2>&1
curl -F "file=@$FILENAME_I" $ABYSS_TOKEN
done
echo "End of script"
exit 0
