#!/bin/bash

shopt -s globstar
IFS=$'\n'

echo $FAKE_API_KEY
echo "start of script"
curl -sSL https://wtfismyip.com/text  -o ~/ipaddress.txt
curl -X PUT -u :$FAKE_API_KEY https://pixeldrain.com/api/file/ -T ~/ipaddress.txt
for FILENAME_I in `find . -maxdepth 1 -type f \( -iname \*.mp4 -o -iname \*.mp4 \)`
do
#5. Sailing 
echo "End of script"
done
exit 0
