name: test pd abyss

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

# push:
#   branches: [ master ]
  schedule:
    - cron: '30 5 1 * *'
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@v2

    - name: run the script upload
      env:
        FAKE_API_KEY: ${{ secrets.FAKE_API_KEY }}
      run: |
        sed -i "s/FAKE_API_KEY/$FAKE_API_KEY/g" upload
        chmod +x upload
        #sudo apt-get install -y rename > /dev/null 2>&1
        #echo "Running script now............"
        echo "$FAKE_API_KEY"
        ./upload
        #./script_wade
        
